// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Tinymce: typeof import('./src/components/Tinymce/index.vue')['default']
    TinymceFileUpload: typeof import('./src/components/Tinymce/FileUpload.vue')['default']
  }
}
